### ISSUE TITLE
no support for python 3.6

### ISSUE THREAD

**Issue by sebastian-brunner** [DLR-RM/python-jsonconversion#1]
When using the library with python 3.6 (default for Ubuntu 18.04), the following stacktrace is printed:

Traceback (most recent call last):
  File "./bin/rafcon", line 31, in <module>
    from rafcon.gui.config import global_gui_config
  File "/home/basti/develop/rafcon/source/rafcon/gui/config.py", line 25, in <module>
    from rafcon.utils import storage_utils
  File "/home/basti/develop/rafcon/source/rafcon/utils/storage_utils.py", line 24, in <module>
    from jsonconversion.encoder import JSONObjectEncoder
  File "/home/basti/.local/lib/python3.6/site-packages/jsonconversion/encoder.py", line 12, in <module>
    from json.encoder import JSONEncoder, _make_iterencode, encode_basestring_ascii, FLOAT_REPR, INFINITY, \
ImportError: cannot import name 'FLOAT_REPR'

Maybe this could be a solution:
https://stackoverflow.com/questions/1447287/format-floats-with-standard-json-module

**Comment by franzlst** [comment]
Was fixed some time ago in 0c493dcd5755adbb37d32d1cfbb26f26c25519de
